
backend:
  name: git-gateway
  branch: main 
  base_url: '/'
  auth_endpoint: '/auth/'

local_backend: true
  
media_folder: "src/assets/img/"
public_folder: "/assets/img/"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Blog" 
    folder: "src/content/posts"
    media_folder: "img/"
    public_folder: "/content/posts/img/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Kategoria", name: "tags", widget: "list"}
      - {label: "Obrazek", name: "thumbnail", widget: "image"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        hint: "Użyj `{% lineStatic %}` tam, gdzie chcesz wstawić linię."
      - label: "Dodaj linię"
        name: "lineStatic"
        widget: "text"
        default: "{% lineStatic %}"

  - name: "works"
    label: "Realizacje"
    folder: "src/content/works"
    media_folder: "img/"
    public_folder: "/content/works/img/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/case.njk"}
      - {label: "Klient", name: "client", widget: "string"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Kategoria", name: "category", widget: "list"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Thumb", name: "thumbnail", widget: "image"}
      - {label: "Mockup", name: "imageMain", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "towns"
    label: "Miasta"
    folder: "src/content/towns"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/town.njk"}
      - {label: "Miasto", name: "town", widget: "string"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Mapa", name: "maplink", widget: "text"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "FAQ"
    name: "faq"
    folder: "src/content/faq"
    create: true
    fields:
      - {label: "Pytanie", name: "title", widget: "string"}
      - {label: "Odpowiedź", name: "answer", widget: "markdown"}

  